### ISSUE TITLE
Misleading example in README.md

### ISSUE THREAD

**Issue by javagl** [donmccurdy/ndarray-pixels#155]
The [usage example](https://github.com/donmccurdy/ndarray-pixels/blob/ba32978797ffe2696cb783884607750fd082ad25/README.md#nodejs) that is currently shown in the README.md is misleading. 

Here is an example based on that, with some added log output:
```javascript
const fs = require("fs");
const { getPixels, savePixels } = require("ndarray-pixels");

async function runExample() {
  const bufferIn = fs.readFileSync("./input.png");

  // read
  const pixels = await getPixels(bufferIn, "image/png"); // Uint8Array -> ndarray

  console.log("pixels", pixels);

  // modify
  for (let i = 0; i < pixels.shape[0]; ++i) {
    for (let j = 0; j < pixels.shape[1]; ++j) {
      console.log("At " + i + " " + j + " value is " + pixels.get(i, j));
      pixels.set(i, j, 255);
    }
  }

  // write
  const bufferOut = await savePixels(pixels, "image/png"); // ndarray -> Uint8Array
  fs.writeFileSync("./output.png", bufferOut);
}

runExample();
```

This can be run for a simple `input.png` image, like this (small) one, for testing:

![input](https://github.com/donmccurdy/ndarray-pixels/assets/5597569/994739af-54ff-4f33-9fb0-f0347d35a43b)

The output will be
```
pixels View3duint8 {
  data: Uint8Array(400) [
    255,   0, 0, 255, 255,   0, 0, 255, 255,   0, 0, 255,
    255,   0, 0, 255, 255,   0, 0, 255, 255,   0, 0, 255,
    255,   0, 0, 255, 255,   0, 0, 255, 255,   0, 0, 255,
    255,   0, 0, 255, 255,   0, 0, 255, 255,   0, 0, 255,
    255,   0, 0, 255, 255,   0, 0, 255, 255,   0, 0, 255,
    255,   0, 0, 255, 255,   0, 0, 255, 255,   0, 0, 255,
    255,   0, 0, 255, 255,   0, 0, 255,   0, 255, 0, 255,
      0, 255, 0, 255,   0, 255, 0, 255,   0, 255, 0, 255,
      0, 255, 0, 255,
    ... 300 more items
  ],
  shape: [ 10, 10, 4 ],
  stride: [ 4, 40, 1 ],
  offset: 0
}
At 0 0 value is undefined
At 0 1 value is undefined
...
```

The output image will be broken accordingly.

---

The reason is that `pixels.shape` will be a **3D** array, consisting of witdth, height, and _channels_. 

The example should be fixed, similar to this example:
```
const fs = require("fs");
const { getPixels, savePixels } = require("ndarray-pixels");

async function runExample() {
  const bufferIn = fs.readFileSync("./input.png");

  // read
  const pixels = await getPixels(bufferIn, "image/png"); // Uint8Array -> ndarray

  console.log("pixels", pixels);

  if (pixels.shape.length !== 3) {
    console.log("Invalid input image");
    return;
  }

  // modify
  for (let i = 0; i < pixels.shape[0]; ++i) {
    for (let j = 0; j < pixels.shape[1]; ++j) {
      for (let k = 0; k < pixels.shape[2]; ++k) {
        console.log("At " + i + " " + j + " " + k + " value is " + pixels.get(i, j, k));
        pixels.set(i, j, k, 255);
      }
    }
  }

  // write
  const bufferOut = await savePixels(pixels, "image/png"); // ndarray -> Uint8Array
  fs.writeFileSync("./output.png", bufferOut);
}

runExample();
```

(Maybe the original sample _does_ work, for specific kinds of grayscale images? From a quick test, this doesn't seem to be the case, but maybe there are other cases where this would work...)

---

If desired, I can create a PR for that.

**Comment by donmccurdy** [comment]
Ah I think you're right, the example should always do `pixels.set(i, j, k, <value>);`. The ndarray ecosystem supports more than that, but for the purposes of image input/output, these should always be 3D ndarrays with 4 channels.

If you wouldn't mind correcting the example that'd be great, thank you!

**Comment by javagl** [comment]
I'll do that later, but just to confirm: There willl **never** be cases where reading the pixels of an image (even in some obscure grayscale format) will yield a 2D shape, is that correct? 

(For the case of keeping the example simple, this boils down to whether that
` if (pixels.shape.length !== 3) { ... }`
check can be omitted or not...)

**Comment by donmccurdy** [comment]
Yes, that's my intention. If the pixels returned from reading any image have channels ≠ 4, I'd consider it a bug in this project. I'm open to revisiting that decision down the road, but for now it seems to fit with the supported formats and usage in this module.
