### ISSUE TITLE
Different behavior in TypeScript and JavaScript

### ISSUE THREAD

**Issue by javagl** [donmccurdy/ndarray-pixels#156]
Sorry, this is just an "observation" for now, and I can not yet point out the exact cause or possible solutions. 

In the context of a TypeScript project, the following example works as "expected":

```typescript
import { savePixels } from "ndarray-pixels";
import NdArray from "ndarray";

async function runTest() {
  const sizeX = 3;
  const sizeY = 3;
  const pixels = NdArray(new Uint8Array(sizeX * sizeY), [sizeX, sizeY]);
  for (let x = 0; x < pixels.shape[0]; x++) {
    for (let y = 0; y < pixels.shape[1]; y++) {
      pixels.set(x, y, x * sizeY + y);
    }
  }
  console.log("pixels ", pixels);
  const image = await savePixels(pixels, "image/png");
  console.log("image ", image);
}

runTest();
```
(It may be "wrong" in some ways, related to https://github.com/donmccurdy/ndarray-pixels/issues/155 , but that shouldn't matter for now). 

However, when this is **not** part of a TypeScript project, but a standalone file (i.e. an empty project after running `npm install --save ndarray-pixels`  ) then this causes an error:

```
Error: Input Bit Array is empty
    at Sharp._createInputDescriptor (C:\ndarray-pixels-test\node_modules\sharp\lib\input.js:61:13)
    at new Sharp (C:\ndarray-pixels-test\node_modules\sharp\lib\constructor.js:351:29)
    at Object.Sharp [as default] (C:\ndarray-pixels-test\node_modules\sharp\lib\constructor.js:173:12)
    at savePixelsInternal (C:\ndarray-pixels-test\node_modules\ndarray-pixels\src\node-save-pixels.ts:12:14)
    at savePixels (C:\ndarray-pixels-test\node_modules\ndarray-pixels\src\index.ts:39:9)
    at runTest (C:\ndarray-pixels-test\Test.ts:19:23)
    at Object.<anonymous> (C:\ndarray-pixels-test\Test.ts:24:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
```

I *think* that this is related to the fact that [this line](https://github.com/donmccurdy/ndarray-pixels/blob/ba32978797ffe2696cb783884607750fd082ad25/src/node-save-pixels.ts#L9) says

`const [width, height, channels] = pixels.shape as [number, number, 4];` 

and in the `dist/ndarray-node-pixels.cjs` file, this becomes

`const [width, height, channels] = pixels.shape;`

leaving the `channels` as `undefined`, causing the zero-length buffer later. But I haven't  investigated the details here yet.

**Comment by donmccurdy** [comment]
The `as [number, number, 4]` cast doesn't set a default value – just type information — so there shouldn't be any runtime difference between those two lines.

Do you get different results with one of these imports?

```js
// (a)
import NdArray from "ndarray";

// (b)
import * as NdArray from "ndarray";

// (c)
import { NdArray } from "ndarray";
```

In glTF Transform (written in TypeScript), I do this:

```typescript
import ndarray, { NdArray } from 'ndarray';

const pixels = ndarray(new Uint8Array(w * h * 4), [w, h, 4]);

setPixels(pixels);

function setPixels(pixels: NdArray<Uint8Array>) {
  // ...
}
```

However ... I think the "correct" import syntax may depend on your bundler. When writing TypeScript I usually [enable esModuleInterop](https://www.typescriptlang.org/tsconfig#esModuleInterop), as shown here: 

https://github.com/donmccurdy/glTF-Transform/blob/13ea9da2179d6b154d60315e562ab7c56513d68c/tsconfig.json#L11

**Comment by javagl** [comment]
In the context where this "worked":

Case `(a)` is the one that I used.

Case `(b)` causes a 
`_NdArrayTest.ts:16:18 - error TS2349: This expression is not callable.` 
at
`const pixels = NdArray(...)`

Case `(c)` causes
`'NdArray' only refers to a type, but is being used as a value here.`
at the same line.

(Not surprising, I guess...)

---

The `tsconfig.json` in that project _does_ include the `"esModuleInterop": true,` flag.

But maybe I should add some disclaimers:

I only quickly and stupidly added this test in the root folder of a larger project, to reproduce https://github.com/KhronosGroup/glTF-Tutorials/issues/87#issuecomment-1711565603 , and started it with `npx ts-node _NdArrayTest.js`. There, I couldn't reproduce the issue. To analyze it further, and created an "empty" project with only `npm install --save ndarray-pixels`, added the test shown above, started it with `node Test.js`, and there, I _could_ reproduce the issue.

(When compiling the test as part of the larger project and running `node ./build/_NdArrayTest.js` directly, then it also seems to work. I tried to debug it a bit, but got lost in the build output. 

So the observation for now is: It seems to behave differently, depending on the context where it is built and started.

(This may be caused by some other entry in the `tsconfig.json`. I have that `"module": "commonjs"` here, and maybe that's the reason? If someone would claim to know the exact meaning and implications of all these settings, I'd like to have a word with them...)

Regardless of why exactly it behaves differently, one could just argue that `[sizeX, sizeY]` is wrong, and it _has_ to be `[sizeX, sizeY, 4]`. So it might, strictly speaking, not be an issue of `ndarray-pixels`, because ... the "issue" only is that something _happens_ to work although it _should_ not work ... maybe.

**Comment by donmccurdy** [comment]
> Regardless of why exactly it behaves differently, one could just argue that [sizeX, sizeY] is wrong ...

Oops, I had missed that. It's a valid input to an ndarray, which can represent more than just RGBA images. Perhaps `savePixels` should validate the shape of the input. I'm still confused by the JS/TS difference though...

**Comment by javagl** [comment]
Maybe I should have pointed that out. The `*4` is mentioned in the TSDoc, but it does not say _explicitly_ that the shape must be a 3-element array, and there seem to be ... some conversions going on (e.g. [this line](https://github.com/donmccurdy/ndarray-pixels/blob/ba32978797ffe2696cb783884607750fd082ad25/src/common.ts#L37) looks like 2-element arrays may be supported, but I didn't wrap my head around all that, and maybe that works only in a specific context). 

I'm tempted to close this issue, because it is not really an issue of `ndarray-pixels` (beyond possible input validations that may be added). Maybe I'll try to investigate the TS-vs-JS difference, but ... won't promise anything, and most likely, the outcome will not affect `ndarray-pixels` anyhow.

**Comment by javagl** [comment]
I'll probably never have the right mix of "being bored" and "finding that corner-case behavior of TS intriguing enough" to allocate the time that may be necessary for investigating why _exactly_ it behaved differently. So... I'll close this.
