### ISSUE TITLE
Vulnerability in *sharp* library

### ISSUE THREAD

**Issue by rawnsley** [donmccurdy/ndarray-pixels#177]
[A vulnerability](https://github.com/advisories/GHSA-54xq-cgqr-rpm3) has been flagged for the _sharp_ library, which _ndarray-pixels_ depends on.

This was flagged in my project by `npm install` and `npm audit`.

**Comment by donmccurdy** [comment]
More context:

- https://github.com/lovell/sharp/issues/3798

Currently ndarray-pixels depends on `^0.32.1` (note the caret allows newer patch releases) and the fix lands in sharp `0.32.6`, so I think that reinstalling `ndarray-pixels` should resolve the newer sharp version and fix the issue.

Alternatively, sharp can be configured to block the vulnerable WebP operation:

```js
sharp.block({ operation: ["VipsForeignLoadWebp"] });
```

Regardless, I'll try to get a new `ndarray-pixels` release out in the next week.
