### ISSUE TITLE
Bump release for sharp 0.33.3 dependency

### ISSUE THREAD

**Issue by FloridaKing** [donmccurdy/ndarray-pixels#211]
`4.0.0` release has a sharp dependency  of `0.32.6`

https://github.com/donmccurdy/ndarray-pixels/blob/v4.0.0/package.json#L42
```
"dependencies": {
		"@types/ndarray": "^1.0.11",
		"ndarray": "^1.0.19",
		"ndarray-ops": "^1.2.2",
		"sharp": "^0.32.6"
	},
```

Sharp `0.33.0` had fix for deno support: https://github.com/denoland/deno/issues/20071#issuecomment-1836135194

Also, latest `@gltf-transform/cli` release also uses sharp `0.33.3`
https://github.com/donmccurdy/glTF-Transform/blob/v4.0.0/packages/cli/package.json#L58

This should hopefully fix a bug when using `npm:@gltf-transform/functions` in deno.

**Comment by donmccurdy** [comment]
Hi @FloridaKing! Thanks, I've just published v4.1 with an updated Sharp dependency.
